### ISSUE TITLE
Error: Invalid login: 535 Error: authentication 

### ISSUE THREAD

**Issue by caozongpeng** [Vincedream/NodeMail#11]
{ Error: Invalid login: 535 Error: authentication failed
    at SMTPConnection._formatError (C:\Users\Kyrie\Desktop\GitClone\NodeMail\nod
e_modules\_nodemailer@4.7.0@nodemailer\lib\smtp-connection\index.js:605:19)
    at SMTPConnection._actionAUTHComplete (C:\Users\Kyrie\Desktop\GitClone\NodeM
ail\node_modules\_nodemailer@4.7.0@nodemailer\lib\smtp-connection\index.js:1340:
34)
    at SMTPConnection._responseActions.push.str (C:\Users\Kyrie\Desktop\GitClone
\NodeMail\node_modules\_nodemailer@4.7.0@nodemailer\lib\smtp-connection\index.js
:378:26)
    at SMTPConnection._processResponse (C:\Users\Kyrie\Desktop\GitClone\NodeMail
\node_modules\_nodemailer@4.7.0@nodemailer\lib\smtp-connection\index.js:764:20)
    at SMTPConnection._onData (C:\Users\Kyrie\Desktop\GitClone\NodeMail\node_mod
ules\_nodemailer@4.7.0@nodemailer\lib\smtp-connection\index.js:570:14)
    at TLSSocket._socket.on.chunk (C:\Users\Kyrie\Desktop\GitClone\NodeMail\node
_modules\_nodemailer@4.7.0@nodemailer\lib\smtp-connection\index.js:522:47)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
  code: 'EAUTH',
  response: '535 Error: authentication failed',
  responseCode: 535,
  command: 'AUTH PLAIN' }
邮件发送成功 undefined

163邮箱认证不通过， 密码账号没问题

**Comment by Vincedream** [comment]
邮箱和授权码是否有错？

**Comment by caozongpeng** [comment]
@Vincedream 谢谢。 知道原因了。

**Comment by ontheway1215** [comment]
同样报错log，535 Error: authentication failed，但是邮件还能发送成功。
