### ISSUE TITLE
Message failed: 554 

### ISSUE THREAD

**Issue by Ghostwritten** [Vincedream/NodeMail#20]
报错了，帮忙看一下，大佬

邮件发送成功 undefined
静等下一次发送
{ Error: Message failed: 554 DT:SPM 126 smtp2,DMmowAAnNDQz4zxdCk6LIw--.52838S2 1564271411,please see http://mail.163.com/help/help_spam_16.htm?ip=219.143.176.2&hostid=smtp2&time=1564271411
    at SMTPConnection._formatError (/root/crawler/NodeMail/node_modules/nodemailer/lib/smtp-connection/index.js:605:19)
    at SMTPConnection._actionSMTPStream (/root/crawler/NodeMail/node_modules/nodemailer/lib/smtp-connection/index.js:1478:34)
    at SMTPConnection._responseActions.push.str (/root/crawler/NodeMail/node_modules/nodemailer/lib/smtp-connection/index.js:968:22)
    at SMTPConnection._processResponse (/root/crawler/NodeMail/node_modules/nodemailer/lib/smtp-connection/index.js:764:20)
    at SMTPConnection._onData (/root/crawler/NodeMail/node_modules/nodemailer/lib/smtp-connection/index.js:570:14)
    at TLSSocket._socket.on.chunk (/root/crawler/NodeMail/node_modules/nodemailer/lib/smtp-connection/index.js:522:47)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:559:20)
  code: 'EMESSAGE',
  response: '554 DT:SPM 126 smtp2,DMmowAAnNDQz4zxdCk6LIw--.52838S2 1564271411,please see http://mail.163.com/help/help_spam_16.htm?ip=219.143.176.2&hostid=smtp2&time=1564271411',
  responseCode: 554,
  command: 'DATA' `}```

**Comment by Ghostwritten** [comment]
发送邮箱是126
smtp：126；
接受邮箱：qq;
授权码已经设好

**Comment by Vincedream** [comment]
问题提供不够充分，如果可以，加我微信解决vince_hua

**Comment by jimStyle88** [comment]
![image](https://user-images.githubusercontent.com/20588608/66902294-fde22c80-f032-11e9-811e-ddbd5e1866a7.png)
我也遇到同样的问题

**Comment by lonePat** [comment]
![image](https://user-images.githubusercontent.com/44112439/71075496-22878b80-21bf-11ea-8ecb-a11a53a768c9.png)
